---
apiVersion: v1
kind: Service
metadata:
  name: user-java-docker
spec:
  selector:
    app: user-java-docker
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-docker
  labels:
    app: user-java-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java-docker
  template:
    metadata:
      name: user-java-docker
      labels:
        app: user-java-docker
    spec:
      containers:
      - name: user-java-docker
        image: danielbryantuk/user-java-docker
        ports:
          - containerPort: 8081
